### ISSUE TITLE
Error with posts

### ISSUE THREAD

**Issue by Enquier** [Open-MBEE/EMS-Repo#7]
"message" : "03270001 Wrapped Exception (with status template): 03270020 Failed to execute script 'classpath_:alfresco\/extension\/templates\/webscripts\/gov\/nasa\/jpl\/view.post.json.js': 03270019 TypeError: Cannot call method \"childByNamePath\" of null (file:\/home\/enquier\/git\/EMS-Repo\/target\/mms-repo-war\/WEB-INF\/classes\/alfresco\/extension\/templates\/webscripts\/gov\/nasa\/jpl\/view.post.json.js#555)",  
  "exception" : "org.springframework.extensions.webscripts.WebScriptException - 03270001 Wrapped Exception (with status template): 03270020 Failed to execute script 'classpath_:alfresco\/extension\/templates\/webscripts\/gov\/nasa\/jpl\/view.post.json.js': 03270019 TypeError: Cannot call method \"childByNamePath\" of null (file:\/home\/enquier\/git\/EMS-Repo\/target\/mms-repo-war\/WEB-INF\/classes\/alfresco\/extension\/templates\/webscripts\/gov\/nasa\/jpl\/view.post.json.js#555)",

**Comment by cinyoung** [comment]
Sorry, curl commands in README are deprecated. Run the curl.tests.sh and copy and paste the curl commands in order.

https://github.com/Open-MBEE/EMS-Repo/blob/opensource/test-data/javawebscripts/curl.tests.sh
